# Generated by Django 5.1.1 on 2024-10-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
