# Generated by Django 5.1.1 on 2024-10-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
