# Generated by Django 5.1.1 on 2024-10-06 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_alter_usuario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='datos_personales',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('correo_electronico', models.CharField(max_length=100)),
                ('numero_telefonico', models.CharField(max_length=10)),
            ],
        ),
    ]
