# Generated by Django 5.1.1 on 2024-10-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_datos_personales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datos_personales',
            options={'managed': False},
        ),
    ]
