# Generated by Django 5.1.1 on 2024-10-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_alter_datos_personales_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datos_personales',
            table='datos_personales',
        ),
    ]
