# Generated by Django 5.1.1 on 2024-10-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_alter_datos_personales_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datos_personales',
            table='TBL_PERSONAS',
        ),
    ]
