# Generated by Django 5.1.1 on 2024-10-16 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0009_alter_datos_personales_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='tbl_usuario',
        ),
    ]
