# Generated by Django 5.1.1 on 2024-10-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0010_alter_usuario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nid_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('ccategoria', models.CharField(max_length=50)),
                ('bhabilitado', models.BooleanField(default=True)),
                ('dfecha_alta', models.DateField(auto_now=True)),
                ('dfecha_baja', models.DateField(null=True)),
            ],
            options={
                'db_table': 'cat_categorias',
                'managed': False,
            },
        ),
    ]
