# Generated by Django 5.1.1 on 2024-10-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0011_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoProducto',
            fields=[
                ('nid_foto_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nid_publicacion', models.CharField(default=1, max_length=50)),
                ('cubicacion_foto', models.ImageField(upload_to='fotos/')),
                ('bhabilitado', models.BooleanField(default=True)),
                ('dfecha_alta', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_foto_publicaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('nid_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nid_categoria', models.CharField(default=1, max_length=50)),
                ('cnombre_producto', models.CharField(max_length=50)),
                ('cdescripcion_producto', models.CharField(max_length=200)),
                ('nprecio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nid_estado_publicacion', models.IntegerField()),
                ('nunidades', models.IntegerField()),
                ('nunidades_vendidas', models.IntegerField()),
                ('bhabilitado', models.BooleanField(default=True)),
                ('dfecha_alta', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_publicaciones',
                'managed': False,
            },
        ),
    ]
