# Generated by Django 5.1.1 on 2024-11-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0012_fotoproducto_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cestado_publicacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cat_estados_publicacion',
                'managed': False,
            },
        ),
    ]
