# Generated by Django 5.1.1 on 2024-11-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0013_estado_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('nid_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('cnombre_producto', models.CharField(max_length=50)),
                ('cdescripcion_producto', models.CharField(max_length=200)),
                ('nprecio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nunidades', models.IntegerField()),
                ('nunidades_vendidas', models.IntegerField(default=0)),
                ('bhabilitado', models.BooleanField(default=True)),
                ('dfecha_alta', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_publicaciones',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
