# Generated by Django 5.1.1 on 2024-11-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0014_publicaciones_delete_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPerfil',
            fields=[
                ('nid_foto_persona', models.AutoField(primary_key=True, serialize=False)),
                ('cubicacion_foto', models.ImageField(upload_to='fotos/')),
                ('bhabilitado', models.BooleanField(default=True)),
                ('dfecha_alta', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_foto_persona',
                'managed': False,
            },
        ),
    ]
